add autocomplete on tab press
bilousbv/project-team-5 pull request #9
Opened 2024-08-15 16:45 UTC by Val-M9

autocomplete by pressing tab

2024-08-15 17:24 UTC, Val-M9 commented
Також якщо у когось macOS прошу перевірити автокомпліт, оскільки на windows довелеся додавати окрему лібу, бо та, що з коробки, авоматично не підтягується. Коротше треба перевірити чи не конфліктує воно. Хоча швидше за все не має.

2024-08-15 20:03 UTC, bilousbv requested changes

2024-08-15 20:03 UTC, bilousbv commented on main.py
> +def completer(text, state):
Я думаю було б краще винести це до команд

2024-08-15 20:06 UTC, bilousbv commented on constants/commands.py
> +
Метод get_command вже описано вище, тому варто видалити один

2024-08-15 20:15 UTC, Val-M9 commented on constants/commands.py
> +
ага, то я так конфлікти резолвлю вночі))

2024-08-15 20:22 UTC, bilousbv commented on main.py
> +    readline.set_completer(completer)
Додав фікс для автокомпліта на macOS, глянь, будь ласка, чи не зламав на Windows

2024-08-15 20:27 UTC, Val-M9 commented on main.py
> +def completer(text, state):
переніс

2024-08-15 20:31 UTC, Val-M9 commented on main.py
> +    readline.set_completer(completer)
не працює на відні тепер)

2024-08-15 20:45 UTC, Val-M9 commented on main.py
> +    readline.set_completer(completer)
додав перевірку, на відні працює тепер норм, має і на маку працювати

2024-08-16 09:48 UTC, bilousbv commented on main.py
> +    readline.set_completer(completer)
Так, все працює. Чудова робота! Залишилось пофіксити конфлікти

2024-08-16 10:02 UTC, bilousBohdan approved these changes

2024-08-16 10:02 UTC, bilousBohdan approved these changes

2024-08-16 10:04 UTC, bilousBohdan approved these changes

2024-08-16 10:08 UTC, bilousBohdan approved these changes

2024-08-16 10:10 UTC, bilousbv approved these changes

2024-08-16 10:10 UTC, merged